"""Inital migration

Revision ID: 41b0fd4f3b38
Revises: 
Create Date: 2024-05-19 08:18:41.828013

"""
from alembic import op
import sqlalchemy as sa
from model import Recipe


# revision identifiers, used by Alembic.
revision = '41b0fd4f3b38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('making_time', sa.String(
                        length=100), nullable=False),
                    sa.Column('serves', sa.String(length=100), nullable=False),
                    sa.Column('ingredients', sa.String(
                        length=300), nullable=False),
                    sa.Column('cost', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    Recipe.inital_seed_data()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
